version: '3'

services:
  mysql:
    container_name: db
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=express-docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  app:
    profiles:
      - in_docker
    container_name: express-docker
    build: .
    environment:
      - PORT=80
      - DB_HOST="dbcms.crsb2fljtjso.us-east-1.rds.amazonaws.com"
      - DB_USER=sqldbcms
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=cms
    ports:
      - "3000:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: