version: '3'

services:
  app:
    image: ghcr.io/salsabeel-alsahory/contentmanagementsystem:$GIT_VERSION
    restart: always
    environment:
      - PORT=80
      - DB_PORT=3306
      - DB_HOST=$DB_HOST
      - DB_USER=sqldbcms
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=cms
    ports:
      - "80:80"
