version: '3'

services:
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=express-docker
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: always

  app:
    image: ghcr.io/salsabeel-alsahory/contentmanagementsystem-:231cdbf
    restart: always
    environment:
      - PORT=3306
      - DB_HOST="dbcms.crsb2fljtjso.us-east-1.rds.amazonaws.com"
      - DB_USER=sqldbcms
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=cms
    ports:
      - "80:80"
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  db-data: